### ISSUE TITLE
Fix you crap

### ISSUE THREAD

**Issue by GrenadeSmasher** [MichaelRunzler/ARKCore#1]
java.io.FileNotFoundException: E:\R34\Sword_Art_Online\2050955%20-%20BWOB%20Bulma_Briefs%20Chichi%20Dragon_Ball%20Dragon_Ball_Z%20Erza_Scarlet%20Fairy_Tail%20Himawari_Uzumaki%20Hinata_Hyuuga%20Leafa%20Lucy_Heartfilia%20Nami%20Naruto%20Nico_Robin%20One_Piece%20Sakura_Haruno%20Sarada_Uchiha%20Sword_Art_Online%20Tsunade%20Wendy_Marvell%20crossover.jpg (The filename, directory name, or volume label syntax is incorrect)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(Unknown Source)
        at java.io.RandomAccessFile.<init>(Unknown Source)
        at javax.imageio.stream.FileImageOutputStream.<init>(Unknown Source)
        at com.sun.imageio.spi.FileImageOutputStreamSpi.createOutputStreamInstance(Unknown Source)
        at javax.imageio.ImageIO.createImageOutputStream(Unknown Source)
        at javax.imageio.ImageIO.write(Unknown Source)
        at com.michaelRunzler.ARK.util.R34.main(R34.java:200)
Exception in thread "main" java.lang.NullPointerException
        at javax.imageio.ImageIO.write(Unknown Source)
        at com.michaelRunzler.ARK.util.R34.main(R34.java:200)

**Comment by MichaelRunzler** [comment]
Issue results from a limitation within the NTFS file system: filenames and their combined directory paths cannot exceed 256 characters due to the 8-bit nature of file descriptors in NTFS. Deploying fix now - program will now auto-truncate file names to less than 256 characters.

**Comment by MichaelRunzler** [comment]
Issue closed: Commit ID 1681be2 addressed issue
