### ISSUE TITLE
Bugs Be Gone

### ISSUE THREAD

**Issue by GrenadeSmasher** [MichaelRunzler/ARKCore#2]
Exception in thread "main" java.lang.IllegalArgumentException: Numbers of source Raster bands and source color space components do not match
        at java.awt.image.ColorConvertOp.filter(Unknown Source)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.acceptPixels(Unknown Source)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.readImage(Native Method)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(Unknown Source)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source)
        at javax.imageio.ImageIO.read(Unknown Source)
        at javax.imageio.ImageIO.read(Unknown Source)
        at com.michaelRunzler.ARK.util.R34.main(R34.java:224)

**Comment by MichaelRunzler** [comment]
System logging support added, please submit system logfiles instead of crash reports from this point on. Working on tracking down the issue, please trigger the crash again and submit its log files.
